# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- job: TestEnvironment
  steps:
  - bash: |
      sudo apt-get update
      echo "Arrancando servicio apache y verificando que este arriba"
      sudo systemctl start apache2.service
      echo `ps -ef | grep -i httpd`
      echo "Se va a ejecutar el comando: ls $(htmlpath)"
      echo `ls $(htmlpath)`
    name: DetermineResult
    
- job: Bar
  dependsOn: TestEnvironment
  condition: eq(dependencies.Foo.outputs['DetermineResult.doThing'], 'Yes') #map doThing and check the value
  steps:
  - script: echo "Job TestEnvironment ran and doThing is Yes."


